- name: Install MacOS Packages
  hosts: localhost
  become: false
  vars:
    install_homebrew_if_missing: true
    upgrade_homebrew_packages: false
    install_zsh_theme_if_missing: true
    upgrade_zsh_theme: true
  vars_files:
    - vars/variable.yml
  pre_tasks:
    - import_tasks: task/config/brew-config.yml
  tasks:
    - import_tasks: task/setup.yml
