- name: Install MacOS Packages
  hosts: localhost
  become: false
  vars:
    install_homebrew_if_missing: true
    upgrade_homebrew_packages: false
  vars_files:
    - vars/variable.yml
  pre_tasks:
    - import_tasks: task/package/brew-setup.yml
  tasks:
    - import_tasks: task/setup.yml
