- name: Check OH My ZSH is installed
  stat:
    path: "$HOME/.oh-my-zsh"
  register: omz_check

- name: OH-MY-ZSH - Installing OH-MY-ZSH
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
  command: source ~/.zshrc
  when: 
   - not omz_check.stat.exists
   - install_zsh_theme_if_missing

- name: OH-MY-ZSH - Updating theme
  shell: echo abc
  when:  
   - omz_check.stat.exists
   - upgrade_zsh_theme


# grep  "ZSH_THEME=""" .zshrc 